### ISSUE TITLE
プロジェクター映えする配色に変更する

### ISSUE THREAD

**Issue by shogo-mitomo** [monstar-lab/yes-no-makura#83]

**Comment by YU-TAYU** [comment]
## 現状の画面
文字サイズも調整した方がよさそう。
<img width="1485" alt="screen shot 2017-09-21 at 10 31 06" src="https://user-images.githubusercontent.com/12754521/30675114-9e915a70-9eb9-11e7-8fd4-81e6023f519b.png">

<img width="1485" alt="screen shot 2017-09-21 at 10 44 45" src="https://user-images.githubusercontent.com/12754521/30675177-069fb5d0-9eba-11e7-9d74-e7047ababfe6.png">
