### ISSUE TITLE
数字ピロピロの動作がもっさりしている（？）

### ISSUE THREAD

**Issue by shogo-mitomo** [monstar-lab/yes-no-makura#84]
まずは現状の動作確認から。

**Comment by YU-TAYU** [comment]
## 現時点で把握している数字の動作がもっさりしてくる条件
### もっさりしてくる部分
質問に対し、結果を表示する場面で「yes」と回答した人数の数値が、アニメーションのようにシャッフルされながら表示される。このシャッフルされる部分は最初はすぐに数字が入れ替わるが、だんだん入れ替わる速度が遅くなってしまう。


### もっさりとしてくる条件(現時点)
質問の表示、集計結果の表示を複数問繰り返すと数字の表示が動作が遅くなり、もっさりしている様子。


### 現時点での予測
result.html.erbのJavascriptのコードの変数(shuffleNumber,waitNumber)を変更すると、もっさりとした動作はなくなる。現時点では`shuffleNumber=60; waitTime = 100;`の場合は、もっさりとした動きはなくなる。
このあたりの変数が何かしていそう。

**Comment by pgkuroneru** [comment]
## もっさりと感じる要因について
### 変数について
* shuffleNumber = 40 : 40回、ランダムに数字を表示する
* waitTime = 125 : 125ミリ秒（数字切り替えのタイミング）

参照：[WindowOrWorkerGlobalScope.setInterval() - Web API インターフェイス | MDN](https://developer.mozilla.org/ja/docs/Web/API/Window/setInterval)

### 数値を変更した際の動きについて
#### shuffleNumberを「100」（waitTimeは125のまま）にした場合
数字を表示する回数が増える。同じ数字が出る回数が増えるため、終盤は特にもっさりとした動きになる。

#### waitTimeを「200」（shuffleNumberは40のまま）にした場合
数字が変わるタイミングが遅くなる。200の場合は、遅く感じる。逆に50の場合は、切り替えが早く一瞬で結果が出る。

### もっさりしていると感じる要因について
ランダムに表示されている数字を見ていった際、終盤近くになると、「特定の数字、もしくはその前後の数字」が繰り返し表示されるようになる。（※最初は「1〜20」でシャッフルをしていたのに対し、終盤では「10〜12」でシャッフルをしているといった動き）

### 現時点での予測
`shuffleNumber=60; waitTime = 100;`とした場合に、動きがもっさりしなくなったと感じたのは数字を表示する回数と、切り替えるタイミングのバランスの釣り合いが取れたからではないだろうか。
同じ数字を複数回見ることによる既視感が、動作がもっさりして見える原因の一つではないかと思われる。
